docs(readme): improve typescript documentation
standard/standard pull request #1616
Opened 2020-12-07 07:44 UTC by toddbluhm

**What is the purpose of this pull request? (put an "X" next to item)**

[x] Documentation update
[ ] Bug fix
[ ] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Reorganized TypeScript/Flow docs to place TypeScript first and added an example for setting up `ts-standard`. Changes based on the comment here: https://github.com/standard/standard/pull/1595#issuecomment-725026148

**Which issue (if any) does this pull request address?**
https://github.com/standard/standard/issues/1590

**Is there anything you'd like reviewers to focus on?**
Language is appropriate and accurate and the example looks simple enough.

2020-12-07 13:10 UTC, munierujp commented on README.md
> +Then run (where `tsconfig.json` is located in the working director):
Fix typo.

```suggestion
Then run (where `tsconfig.json` is located in the working directory):
```

2020-12-13 15:49 UTC, Divlo approved these changes

2020-12-27 06:49 UTC, munierujp requested changes
see my comments :bow:

2020-12-27 06:49 UTC, munierujp commented on README.md
> +For Typescript, an official variant `ts-standard` is supported and maintained that provides a very
Fix typo

```suggestion
For TypeScript, an official variant `ts-standard` is supported and maintained that provides a very
```

2020-12-30 17:18 UTC, toddbluhm commented on README.md
> +For Typescript, an official variant `ts-standard` is supported and maintained that provides a very
Done

2021-01-15 16:59 UTC, munierujp reviewed
LGTM 😄

2021-01-15 17:00 UTC, munierujp approved these changes

2021-01-16 05:52 UTC, merged